version: '2.0'
services:
  db-spring:
    container_name: spring-pg
    image: 'postgres:13'
    environment:
      POSTGRES_PASSWORD: java
      POSTGRES_USER: java
      POSTGRES_DB: spring
    volumes:
      - ./data_pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"